name: kuber-docker

services: 
  api:
    build: 
      context: ./backend
      dockerfile: .dockerfile
    restart: unless-stopped
    
    env_file: ./backend/.env
    ports: 
      - 4004:4000
  
  frontend:
    build:
      context: ./frontend
      dockerfile: .dockerfile
    restart: unless-stopped
    env_file: ./frontend/.env
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host
    ports:
      - 5173:5173
    depends_on:
      - api

  nagios:
    image: jasonrivers/nagios:latest
    restart: unless-stopped
    ports: 
      - "8081:80"
    environment:
      - NAGIOSADMIN_USER=admin
      - NAGIOSADMIN_PASS=nagios
    depends_on:
      - api
      - frontend
